### ISSUE TITLE
Pipeline does not complete

### ISSUE THREAD

**Issue by thefeds-nau** [JulianHayward/AzGovViz#1]
Trying to run from ADO using a Service Principal, read documentation and confirmed permissions are ok. I have used this same SP on previous versions of AzGovViz. I am now trying to complete the set up in a new ADO Project to share with my team. I would like to have the wiki built and publish to Azure Web App but this Run Azure Governance Visualizer step fails to complete. any advice/assistance would be great.

Line |
   5 |  . '/home/vsts/work/1/s/pwsh/AzGovVizParallel.ps1' -ManagementGroupId  …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Key cannot be null. (Parameter 'key')

##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed;]PowerShell exited with code '1'.
Finishing: Run Azure Governance Visualizer

**Comment by JulianHayward** [comment]
@thefeds-nau difficult to judge / not too much info - please open the issue at aka.ms/azgovviz - this is just a demo repo

**Comment by thefeds-nau** [comment]
apologies, will do.
